import type { Metadata } from 'next';
import './globals.css';
import { QueryClientProvider } from '@/components/query-client-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
